config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/requests/your_requests', to: 'requests#your_requests', as: 'your_requests'
  get '/posts/your_posts', to: 'posts#your_posts', as: 'your_posts'
  get '/profile_settings', to: 'users#profile_settings', as: 'profile_settings'
  resources :users, except: [:destroy]
  resources :posts
  resources :requests

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'application#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :requests

  CATEGORIES = [
    'Musical',
    'Sports',
    'Language',
    'Art',
    'Cooking'
  ]
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :requester, class_name: 'User'
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :requests

  mount_uploader :avatar, AvatarUploader

  def display_name
    "#{first_name} #{last_name}"
  end

  def requests_made
    Request.where(requester_id: id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def home
    @posts = Post.order(created_at: :desc).limit(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    if params[:filter]
      @posts = Post.where(category: params[:filter])
    else
      @posts = Post.all
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @categories = Post::CATEGORIES
  end

  # GET /posts/1/edit
  def edit
    @categories = Post::CATEGORIES
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def your_posts
    @posts = Post.where(user: current_user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :category, :description, :price, :availability)
    end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    # Requests for your lessons
    @requests = current_user.requests
  end

  def your_requests
    # Requests you've made
    @requests = current_user.requests_made
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new(post_id: params[:post_id], user_id: params[:user_id])
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    new_request_params = request_params.merge({requester_id: current_user.id})
    @request = Request.new(new_request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:message, :post_id, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def profile_settings
    @user = current_user
  end

  def update
    current_user.update(user_params)
    redirect_to user_path(current_user)
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :bio, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/application/home.html.erb
<h2 id="home_title">Learn a new skill</h2>
<p id="home_head">
  Take time to find a new skill to learn.
</p>

<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
          <img class="d-block img-fluid" src="/guitar.jpg" alt="Teach Guitar">
        </div>
        <div class="carousel-item">
          <img class="d-block img-fluid" src="/karate.jpg" alt="Learn Something New">
        </div>
        <div class="carousel-item">
          <img class="d-block img-fluid" src="/role_model.jpg" alt="Be a Role Model">
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
  <div class="col-md-2"></div>
</div>

<h3>Latest Lessons</h3>
<table class='table'>
  <tbody>
    <%- @posts.each do |post| %>
      <tr>
        <th scope='row'><%= post.title %></th>
        <td><%= post.description%></td>
        <td><%= number_to_currency(post.price) %></td>
        <td><%= post.availability%></td>
      </tr>
    <%- end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Skillable</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'Skillable', root_path, class: 'navbar-brand mb-0 h1' %>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a href="<%= posts_path %>" class='nav-link'><%= fa_icon "files-o" %> Lessons</a>
      </li>
      <li>
        <a href="<%= your_posts_path %>" class='nav-link'><%= fa_icon "file-o" %> Your Lessons</a>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= fa_icon "envelope-o" %>
            Requests
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to("Requests for You", requests_path, class: 'dropdown-item') %>
            <%= link_to("Your Requests", your_requests_path, class: 'dropdown-item') %>
          </div>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav ml-md-auto d-none d-md-flex">
      <% if user_signed_in? %>
        <li class="nav-item">
          <a href="<%= new_post_path %>" class='nav-link'><%= fa_icon "plus" %> Submit a Lesson</a>
        </li>
        <li class="nav-item">
          <a href="<%= profile_settings_path %>" class='nav-link'><%= fa_icon "gears" %> Your Profile</a>
        </li>
        <li class="nav-item">
          <a href="<%= destroy_user_session_path %>" class='nav-link' data-method='delete'><%= fa_icon "sign-out" %> Logout</a>
        </li>
      <% else %>
        <li class="nav-item">
          <a href="<%= new_user_session_path %>" class='nav-link'><%= fa_icon "sign-in" %> Login</a>
        </li>
        <li class='nav-item'>
          <a href="<%= new_user_registration_path %>" class='nav-link'><%= fa_icon "plus" %> Sign Up</a>
        </li>
      <% end %>
    </ul>
</nav>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
      </div>
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group row'>
    <label for="post_title" class="col-sm-2 col-form-label col-form-label-sm">Title</label>
    <div class="col-sm-10">
      <%= form.text_field :title, id: :post_title, placeholder: 'Title', class: 'form-control form-control-sm' %>
    </div>
  </div>

  <div class="form-group row">
    <label for="post_category" class="col-sm-2 col-form-label col-form-label-sm">Category</label>
    <div class="col-sm-10">
      <%= form.select(:category, options_for_select(@categories), {}, class: "custom-select") %>
    </div>
  </div>

  <div class='form-group row'>
    <label for="post_description" class="col-sm-2 col-form-label col-form-label-sm">Title</label>
    <div class="col-sm-10">
      <%= form.text_area :description, id: :post_description, placeholder: 'Description', class: 'form-control form-control-sm' %>
    </div>
  </div>

  <div class='form-group row'>
    <label for="post_title" class="col-sm-2 col-form-label col-form-label-sm">Title</label>
    <div class="input-group col-sm-10">
      <div class="input-group-addon">$</div>
      <%= form.text_field :price, id: :post_price, placeholder: '0.00', class: "form-control" %>
    </div>
  </div>

  <div class='form-group row'>
    <label for="post_availability" class="col-sm-2 col-form-label col-form-label-sm">Availability</label>
    <div class="col-sm-10">
      <%= form.text_field :availability, id: :post_availability, placeholder: 'Availability', class: 'form-control form-control-sm' %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit nil, class: 'btn-primary' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-mid-12">
    <h1>Lessons</h1>
  </div>
</div>


<div class="row">
  <div class="col-mid-12">
    <h5>Categories:</h5>
    <div class="btn-group" role="gorup">
      <%= link_to 'Clear', posts_path(), class: "btn btn-secondary" %>
      <% Post::CATEGORIES.each do |category| %>
        <% selected = params[:filter] == category ? 'active' : '' %>
        <%= link_to category, posts_path(filter: category), class: "btn btn-secondary #{selected}" %>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-mid-12">
    <table class='table'>
      <thead>
        <tr>
          <th>Title</th>
          <th>Instructor</th>
          <th>Description</th>
          <th>Category</th>
          <th>Price</th>
          <th>Availability</th>
        </tr>
      </thead>

      <tbody>
        <% if @posts.empty? %>
          <td>No lessons matching your criteria.</td>
        <% else %>
          <% @posts.each do |post| %>
            <tr>
              <td><%= link_to(post.title, post_path(post)) %></td>
              <td><%= link_to(post.user.display_name, user_path(post.user)) %></td>
              <td><%= post.description %></td>
              <td><%= post.category %></td>
              <td><%= number_to_currency(post.price) %></td>
              <td><%= post.availability %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/posts/new.html.erb
<h1>Post a new lesson</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Back', posts_path %>

<div class="row">
  <div class="col-md-6">
    <div class="row">
      <div class="col-md-12">
        <h2><%= @post.title%></h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <h4><%= number_to_currency(@post.price) %></h4>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <p><%= @post.description%></p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <p>Availability: <%= @post.availability%></p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <%= button_to 'Request a lesson', new_request_path(post_id: @post.id, user_id: @post.user.id), class: 'btn btn-success' %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="row">
      <div class="col-md-6">
        <div class="card" style="">
          <%= image_tag @post.user.avatar.url, size: "250x250 ", class: 'card-img-top' %>
          <div class="card-body">
            <h4 class="card-title">About the Instructor</h4>
            <p class="card-text"><%= @post.user.bio %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% if @post.user == current_user %>
  <%= link_to 'Edit', edit_post_path(@post) %>
<% end %>

app/views/posts/your_posts.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-mid-12">
    <h1>Your Lessons</h1>
  </div>
</div>


<div class="row">
  <div class="col-mid-12">
    <table class='table'>
      <thead>
        <tr>
          <th>Title</th>
          <th>Category</th>
          <th>Description</th>
          <th>Price</th>
          <th>Availability</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= post.title %></td>
            <td><%= post.category %></td>
            <td><%= post.description %></td>
            <td><%= number_to_currency(post.price) %></td>
            <td><%= post.availability %></td>
            <td><%= link_to 'Show', post %></td>
            <td><%= link_to 'Edit', edit_post_path(post) %></td>
            <td><%= button_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/requests/_form.html.erb
<%= form_with(model: request, local: true) do |form| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message, id: :request_message %>
  </div>

  <%= form.hidden_field(:post_id, value: params[:post_id]) %>
  <%= form.hidden_field(:user_id, value: params[:user_id]) %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests for You</h1>

<table class="table">
  <thead>
    <tr>
      <th>From</th>
      <th>Message</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.requester.display_name %></td>
        <td><%= request.message %></td>
        <td><%= button_to 'Delete', request, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @request.message %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>

app/views/requests/your_requests.html.erb
<p id="notice"><%= notice %></p>

<h1>Your Requests</h1>

<table class="table">
  <thead>
    <tr>
      <th>To</th>
      <th>Message</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.user.display_name %></td>
        <td><%= request.message %></td>
        <td><%= button_to 'Delete', request, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/profile_settings.html.erb
<%= form_for(@user, url: user_path(@user)) do |f| %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>

  <%= image_tag @user.avatar.url, size: "250x250" %>
  <div class="field">
    <%= f.label :avatar %><br />
    <%= f.file_field :avatar %>
  </div>

  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-6">
    <h1><%= @user.display_name %></h1>
    <h3>Bio:</h3>
    <p><%= @user.bio %></p>
  </div>

  <div class="col-md-6">
    <%= image_tag @user.avatar.url, size: "250x250" %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h3>Lessons:</h3>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <table class='table'>
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Category</th>
          <th>Price</th>
          <th>Availability</th>
        </tr>
      </thead>

      <tbody>
        <% if @user.posts.empty? %>
          No classes posted.
        <% else %>
          <% @user.posts.each do |post| %>
            <tr>
              <td><%= link_to(post.title, post_path(post)) %></td>
              <td><%= post.description %></td>
              <td><%= post.category %></td>
              <td><%= number_to_currency(post.price) %></td>
              <td><%= post.availability %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>